City Gen version 2
OSUGameDev/LocalWar pull request #32
Opened 2019-12-05 01:32 UTC by isvpursuit

1. Set the title to exactly what you are adding.

2. Which team is this for?
Gameplay

3. Give a short description of what you are implementing:

- Building Walls no longer overlap
- Invisible Walls added
- Wall colors added as a test feature
- City Parameters are now synced, allowing for the parameters to be chosen by host in future

2019-12-14 07:31 UTC, JasonStallkamp commented on Local War/Assets/Resources/Script/CityGen/MeshGenerator.cs
> +		}
Indentation is not consistent

2019-12-14 07:32 UTC, JasonStallkamp commented on Local War/Assets/Resources/Script/CityGen/MeshGenerator.cs
> +		}
Other than that it is good to merge

2019-12-14 07:33 UTC, JasonStallkamp requested changes
Fix indentation Local War/Assets/Resources/Script/CityGen/MeshGenerator.cs on line 191 to 208

2019-12-14 15:40 UTC, isvpursuit commented
What's inconsistent in the indentation? The if statements? I just opened it up again and it looks correct to me.

2019-12-15 01:31 UTC, JasonStallkamp commented on Local War/Assets/Resources/Script/CityGen/MeshGenerator.cs
> +		}
Here is the code with an extra indent

2020-01-16 01:08 UTC, JasonStallkamp commented on Local War/Assets/Resources/Script/CityGen/MeshGenerator.cs
> +		}
Could not find the indentation in the unity editor

2020-01-16 01:09 UTC, JasonStallkamp approved these changes

2020-01-16 01:09 UTC, merged